# Generated by Django 4.2.7 on 2023-11-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=10)),
                ('Phone_no', models.CharField(max_length=13)),
                ('aadhar', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('dept', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
    ]
