# Generated by Django 4.2.7 on 2023-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_yout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='age',
            field=models.IntegerField(),
        ),
    ]
