# Generated by Django 4.2.7 on 2023-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_yout', '0002_alter_emp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
